name: Deploy CDK Stack

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/delete.txt'

env:
  CDK_DEFAULT_REGION : "us-east-1"
  CDK_DEFAULT_ACCOUNT: "943892479744"
  DOMAIN: "sidor.me"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::943892479744:role/Resume-IAC-Role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.CDK_DEFAULT_REGION }}
          # aws-access-key-id: {{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: {{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: {{ secrets.AWS_REGION }}
      
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      - name: Synthesize the app
        run: cdk synth

      - name: Deploy CDK Stack
        run: cdk deploy --all --require-approval never
